# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python format

on:
  push:
    paths:
      - "**.py"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pylint
      run: pip install pylint
    - name: Run pylint
      run: |
        TARGET="master"
        COUNT=0
        THRESHOLD=9.0

        git fetch origin ${TARGET}
        BLANCH_START=$(git merge-base `git branch --show-current` origin/${TARGET})
        FILES=$(git diff --name-only ${BLANCH_START} -- "**.py")
    
        if [ ${#FILES[@]} -eq 0 ]; then echo "no diff file 1"; success; fi
        for file in ${FILES[@]}; do echo ${file}; COUNT=$(( ${COUNT} + ${#file} )); done
        if [ ${COUNT} -eq 0 ]; then "no diff file 2"; success; fi
        pylint --rcfile=.pylintrc --fail-under=${THRESHOLD} ${FILES} > temp.txt
